### PR TITLE
Remove DST fix in `eachDay` (closes #80)

### LINKED ISSUE #80: Remove DST fix in `eachDay`
Seems like this part
```javascript
    /**
     * add additional 5 hours to get next day,
     * because of possible troubles with daylight savings dates
     */
    tmpDate = new Date(curDate.setTime(curDate.getTime() + 5 * 60 * 60 * 1000))
    tmpDate = new Date(tmpDate.setHours(0, 0, 0, 0))
```
is not necessary

### PR DESCRIPTION
**Pull request by LeshaKoss**

### CODE REVIEW

File: src/each_day.js [hunk 1]
```diff
@@ -9,23 +9,13 @@ var parse = require('./parse')
...
-    /**
-     * add additional 5 hours to get next day,
-     * because of possible troubles with daylight savings dates
-     */
-    tmpDate = new Date(curDate.setTime(curDate.getTime() + 5 * 60 * 60 * 1000))
-    tmpDate = new Date(tmpDate.setHours(0, 0, 0, 0))
-    curDate = tmpDate
+  while (currentDate.getTime() <= endTime) {
+    dates.push(new Date(currentDate))
+    currentDate.setDate(currentDate.getDate() + 1)
```
Comment (kossnocorp) [inline src/each_day.js]: @LeshaKoss we need to add an exception if end date is before start date otherwise the code can hang. Please add an issue for that (and all similar cases).
